version: '3.5'

services:
  alfred_netatmo_data_collector_service:
    build: .
    image: alfred_netatmo_data_collector_service:latest
    container_name: alfred_netatmo_data_collector_service
    restart: always
    hostname: alfred_netatmo_data_collector_service
    networks:
      - alfred
    command: npm run prod

networks:
  alfred:
    name: alfred
    driver: bridge
